spring.application.name=ms-barriodigital-bff
server.port=8080
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${AZURE_TENANT_ID:TODO-CONFIG}/v2.0
app.security.expected-audience=${AZURE_BFF_CLIENT_ID:TODO-CONFIG}
app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:4200}
app.services.requests-url=${SERVICES_REQUESTS_URL:http://localhost:8081}
app.services.catalog-url=${SERVICES_CATALOG_URL:http://localhost:8082}
